---
output:
  html_document: default
  pdf_document: default
---
\usepackage{xeCJK}

---
title: "Summary of Trend Following with Managed Futures - Chapter 5"
author: "Sida.Li"
date: "May 11th, 2017"
output: html_document
---

##Chapter-5 Divergence and the Tradability of Trend

###Some key concepts
* CTA       £º Commodity Trading Advisor
* Convergence
* Divergence
* Convexity £º A measurement of output against input. (Positive convexity means something like lottery)
* SNR
* MDI
* Fourier Transform
* Trend Leakage



###Topics,Ideas&contents of this charpter

Item  Topics                                                Contents                                        
---   ---------------------------                           ------------------------------                       
1.    Risk vs Uncertainty                                    The defination of Risk and Uncertainty
2.    Convergence vs Divergence                              Describe two diffrent live/trading strategies
3.    Measuring Market Divergence                            The calculation of SNR/MDI
4.    Testing the Stationarity of Market Divergence          Emperical test on the MDI
5.    The Tradability of Trend                               Emperical test on Trend Leakage
6.    The importance of Entry vs.Exit                        Exit strategy's importance to the profitability of trend following strategies
---  ---------------------------                            -----------------------------                  


###1.Risk vs Uncertainty

It will be quite essential for researchers to sort out the differences between the concepts of Risk and Uncertainty.
In general, **Risk** is defined as as the chance that things will not turn as you expect (prices run against you).**Uncertainty** represents the situation that the outcome of things is knownown.

Risk is knowable and uncertainty is not.

###2.Convergence and Divergence

The two idea about the very world we are living in dictates how we make decisions. CTA is widely accepted as a divergence strategy.

A convvergence believer have faith in the system and believe outcomes are predictable, while divergence believer will always skeptical
about what is stable and what isn't.

As a result convergence strategies often come with many small gains and occasionally catastrophic losses. Divergence strategies in the other hand, bets heavy on the favor trend and cut losses quickly, which means they often result in many small losses and occasionally big
wins.

###3.Measuring Divergence

Basically, measuring divergence equals to measuring uncertainty£¬ which means the volatility of certain asset that cannot be explained by models

To measure the uncertainty of certain asset we can use RUR(Risk to Uncertainty Ratio),it gives the divergence characteristic of certain market/asset and thus provide intuitive insights about wether we should apply divergence strategies:

$$
\tag{1}   {RUR} = \frac{Explained Volatility}{Unexplained Volatility} = \frac {Explained volatility} {Total volatility - Explained volatility}
$$

####Measuring Divergence at Portfolio Level
The quality of a trend is essential for trading strategies relying on divergence.
To calculate the quality of the trend in a single market, we can apply formula (2):
$$
\tag{2}   {SNR} = \frac{|P_t - P_{t-n}|}{\sum_{k=0}^{n-1}|P_{t-k}-P_{t-k-1}|}
$$
A straight forward explanation of this formula would be: assuming trends are always linear, then all deviation of price movement will be sum as $P_{t-k}-P_{t-k-1}$. The total trend $|P_t - P_{t-n}|$ devided by deviation will reflect the divergence. The higher the SNR, the higher the quality of the trend (SNR=1 means no noise).


The cross market divergence will be the average of SNRs across market:

$$
\tag{3}   {MDI} = \frac{1}{M}\sum_{i=1}^MSNR_t^i(n)
$$

###4.Testing the Stationarity of Market Divergence

If EMH truely holds, divergence would be a rapid process with little room to trade, which means we can evaluate the velocity of MDI to
confirm whether Market Divergence is realy tradable.

A fourier transform is used to transform time sequence data into frequency data. By doing so the stationarity of MDI could be tested.

The rest of the chapter focus a lot on proving stationarity of divergence and the speed of divergence statistically, fourier transform and KPSS test (require auto-corrlation lags) are used.

###Trend leakage and tradability

By applying KPSS method, trend leakage is proven to be exists. The gap in some extreme events are quite significant, which reveals a 
certain tradability of trend following strategies.

A discussion about ramdom entry system is provided in the chapter. Which offers insights about the importance of exit strategy (as a mothod of risk control).

Although no operating detials are disclosed, the research on trading systems provide an opinion that risk control(when to exit) is helpful
in creating profit and controlling drawdowns.



